name: mlflow-study
channels:
  - http://nexus.k8s.uc.host.dxy/repository/anaconda/pkgs/main/
  - http://nexus.k8s.uc.host.dxy/repository/anaconda/pkgs/free/
  - http://nexus.k8s.uc.host.dxy/repository/anaconda/pkgs/r/
  - http://nexus.k8s.uc.host.dxy/repository/anaconda/pkgs/pro/
  - http://nexus.k8s.uc.host.dxy/repository/anaconda/pkgs/msys2/
dependencies:
  - python=3.6
  - scikit-learn=0.19.1
  - cloudpickle=0.6.1
  - numpy=1.14.3
  - pandas=0.22.0
  - pyspark=2.4.3
  - matplotlib=3.1.1
  - pip:
    - mlflow
    - pyarrow==0.12.1
